### ISSUE TITLE
encountering quota exceeded error when accessing api

### ISSUE THREAD

**Issue by vinwonghk** [marciovsena/bibleapi#73]
Hi, thanks for maintaining the api continuously!

I am having the following error when trying to access the api to get books

```
{
    "msg": "Oops! An unexpected error has occurred, create an [issue](https://github.com/marciovsena/bibleapi/issues/new) with the information of this request.",
    "err": {
        "driver": true,
        "name": "MongoError",
        "index": 0,
        "code": 12501,
        "errmsg": "quota exceeded"
    }
}
```

**Comment by marciovsena** [comment]
@vinwonghk we have been suffering attacks since 29/03. The service until yesterday remained stable, but today it fluctuated, because before we returned the request we saved some information from the requester. We fixed the problem and the service is working normally.

I ask you to use the logged in option. You will need to create a user and use the token for all requests.

I am asking you this, because starting next week I will limit queries without a user to avoid these problems. Who has a registered user will continue to access for free and without limitation of requests.

Thanks for reporting
